# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            David Kretch
tagline:          ''
description:      ''
url:              http://kretch.org
baseurl:          /

author:
  name:           'David Kretch'
  url:            https://twitter.com/davidkretch

paginate:         5

# Custom vars
version:          2.1.0

email:           mailto:david.kretch@gmail.com
twitter:         https://twitter.com/davidkretch
github:          https://github.com/davidkretch
linkedin:        https://www.linkedin.com/in/davidkretch
